### ISSUE TITLE
Expose contract addresses

### ISSUE THREAD

**Issue by x-xo** [deep-ink-ventures/genesis-dao-service#1]
The backend has access to the following env vars
- CORE_CONTRACT
- ASSETS_CONTRACT
- VOTES_CONTRACT

These should be exposed via a dedicated endpoint so the frontend can use them.

**Comment by Shirku** [comment]
[b581295f13448fd8c30fc84ab3d36fa96ca6f8c0](https://github.com/deep-ink-ventures/elio-dao-service/commit/b581295f13448fd8c30fc84ab3d36fa96ca6f8c0)
:heavy_check_mark:
