### ISSUE TITLE
Endpoint to store multisig call params and hash

### ISSUE THREAD

**Issue by x-xo** [deep-ink-ventures/genesis-dao-service#13]
The events for the multisig operations only contain hashes of the original call data. In order for the frontend to display the original data, we need to map said data to the call hash in the backend. So the frontend can resolve it later on.

The first endpoint should store
- the original call data, and
- the hash (as calculated by the frontend)

The backend then must verify the hash is correct, using [this code](https://github.com/polkascan/py-substrate-interface/blob/master/examples/multisig.py#L38).

Only if correct, the backend stores the call data and associates it with the hash for later retrieval.

**Comment by deep-ink-ventures** [comment]
The call must be signed by either the DAO Owner, of (more likely, because it's a multisig) one of the multisig signers to be accepted.

**Comment by pacifiquet** [comment]
@x-xo @deep-ink-ventures 
I would like to ask for help on how verify the hash is correct. i can't find a way to use the code provided above.
and  and what original call data i am expecting

**Comment by deep-ink-ventures** [comment]
This is the Lifecycle:

1. A tx is created via endpoint or via an incoming NewMultisig event -> Status is PENDING, when the event comes in there is already the first signer (who submitted, we store this signer in the model)

2. A tx is updated via MultisigApprovalevent -> Status remains PENDING if the threshold isn't met but we store the addition signer, if the number of signers meets the threshold, the status becomes APPROVED

3. A tx is updated via MultisigCancelled event -> Status switches to CANCELLED
A tx is updated via MultisigExecuted event -> Status switches to EXECUTED

these are the events: https://github.com/paritytech/substrate/blob/master/frame/multisig/src/lib.rs#L225-L247

Just to note: A tx can be created via an endpoint or via an event and both must be possible and sometimes only an event happens (when someone uses a different ui and is not using our API endpoint). In that case we still track it but give back the values as None in the API on the params / function / module. We can then only present the call hash in the ui

Sample code for the call hash:

```python
from substrateinterface import SubstrateInterface
substrate = SubstrateInterface(url="wss://node.genesis-dao.org/")

try:
    call = substrate.compose_call(
        call_module='Votes',
        call_function='mark_implemented',
        call_params={
            'proposal_id': 42,
        }
    )
    call_hash = call.call_hash

    # bytes
    print(call_hash)

    # encoded, to store in the database
    print(call_hash.hex())

    # reverse the hex encoding
    print(bytes.fromhex(call_hash.hex()))

except ValueError as exc:
    print(f'Raise a 400 and give back this: {exc}')
    ```

**Comment by Shirku** [comment]
39f24db137e9c09465e76fc952345fc480faf69a
