### ISSUE TITLE
Keep track of proposal creation states

### ISSUE THREAD

**Issue by x-xo** [deep-ink-ventures/genesis-dao-service#15]
We’re currently allowing users to create a proposal on-chain, submit metadata off-chain, but not set the metadata on-chain. Some incomplete proposals in the database are not on the chain.

Maybe we can add a `setupComplete` flag on proposals too?

**Comment by Shirku** [comment]
https://github.com/deep-ink-ventures/genesis-dao-service/commit/91db543312f635d93975d6250cfcf0df2e9e450a
