### ISSUE TITLE
Support searching for assets, proposals, transactions

### ISSUE THREAD

**Issue by x-xo** [deep-ink-ventures/genesis-dao-service#17]
Let's add the search filter (https://www.django-rest-framework.org/api-guide/filtering/#searchfilter) to all relevant endpoints so we can search

- Transactions, by title
- Proposals, by title
- DAOs, by name (and optionally by ID, too)

**Comment by Shirku** [comment]
@x-xo by `Transactions, by title` you mean the call function name, i assume?
DAOs are already filterable by `"id", "name", "creator_id", "owner_id"`.

it's not mentioned here so is this supposed to be a different kind of search than we are currently using?
`SELECT * FROM core_dao WHERE name = 'dao';`
or should we switch to `ILIKE`?
`SELECT * FROM core_dao WHERE name ILIKE '%dao%';`

**Comment by deep-ink-ventures** [comment]
What speaks against using https://www.django-rest-framework.org/api-guide/filtering/#searchfilter? There shouldn't be any customization here.

**Comment by Shirku** [comment]
@deep-ink-ventures well, it can't do ordering afaik.
i am also not a huge fan of using a new lib for every single small thing to add.
plus we already got search in place.
so should the serach behavior change or not?

**Comment by x-xo** [comment]
The current approach matches by exact name, which isn't useful when someone is searching for a (part of) a name. So I vote for changing it.

**Comment by Shirku** [comment]
`To use DjangoFilterBackend, first install django-filter.`
but sure i can use that instead of writing one more line of code

**Comment by deep-ink-ventures** [comment]
We are not talking about `DjangoFilterBackend`, but about the `SearchFilter` and that is core: https://github.com/encode/django-rest-framework/blob/master/rest_framework/filters.py#L60

**Comment by Shirku** [comment]
69ee549f9e44199b71fd820747fcf98b4e85800f
