### ISSUE TITLE
Support multisig transactions

### ISSUE THREAD

**Issue by x-xo** [deep-ink-ventures/genesis-dao-service#18]
As discussed here https://miro.com/app/board/uXjVM2LTmYk=/ the backend should pick up the multi-signature transactions and expose them (paginated) to the frontend with the relevant details.

**Comment by Shirku** [comment]
23fa8c114bc45cc8d60b8110c0e49fab03c7cacd

**Comment by Shirku** [comment]
23fa8c114bc45cc8d60b8110c0e49fab03c7cacd
