### ISSUE TITLE
Transfor faulty proposal into transaction

### ISSUE THREAD

**Issue by deep-ink-ventures** [deep-ink-ventures/genesis-dao-service#19]
When a user reports a transaction as faulty, please create a new, empty transaction for this that can be queried by the frontend that's lists all the pending transactions.

Module: dao_votes
Extrinsic: fault_proposal
Parameter:
- proposal_id
- reason

Num Signers 0/3

Call Hash can be `null` or  you can precalculate this if it's easy.

**Comment by Shirku** [comment]
afc68eb1489a3911cc6dd267481a99876d5579f2
