### ISSUE TITLE
Certain addresses generate a 500

### ISSUE THREAD

**Issue by deep-ink-ventures** [deep-ink-ventures/genesis-dao-service#24]
["5Dc4froJzAxNrpxC1JMvM27GMMjk6fN5cxiQDV6zdbeHvBn6", "5GpGweMfmUe8rV5ScXJgfhEAVU3Aom4yVF2YH9pscNQGzZgw"] threshold of 2

The `5GpGweMfmUe8rV5ScXJgfhEAVU3Aom4yVF2YH9pscNQGzZgw` generates a 500, even though it exists:

https://service.genesis-dao.org/accounts/5GpGweMfmUe8rV5ScXJgfhEAVU3Aom4yVF2YH9pscNQGzZgw/

**Comment by Shirku** [comment]
53122e13158f9772c6efe0c9508f9270d06f849c
