### ISSUE TITLE
Create new multisig wallet

### ISSUE THREAD

**Issue by x-xo** [deep-ink-ventures/genesis-dao-service#5]
Provide an endpoint that supports creating a new multisig wallet.
The endpoint should require:
- the ID of the DAO to use the multisig wallet for
- the signer addresses
- the threshold (i.e. how many signers are required to approve a transaction)

**Comment by x-xo** [comment]
Requires a bit more thought on how the information are exchanged and when/where the tx is being sent.

**Comment by deep-ink-ventures** [comment]
```
POST {
   'id': 'DIV',   -> ForeignKey DAO
   'signers': ['5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY', 'add2', 'add3'], Arrayfield
   'threshold': 3 -> Integer Field
}
```

**Comment by deep-ink-ventures** [comment]
The return value should have the address of the multisig!
