### ISSUE TITLE
Listen for on-chain events

### ISSUE THREAD

**Issue by x-xo** [deep-ink-ventures/genesis-dao-service#7]
The service should listen for on-chain events and store all transactions for any known multisig wallet.

The events are as follows:
- NewMultisig
- MultisigApproval
- MultisigExecuted
- MultisigCancelled

Based on the specific event, the following should happen:

#### NewMultisig
Create a new transaction, store approver (as array) and call hash and associate it with the multisig wallet, a `created_at` timestamp and a `status` (`pending`, `approved`, `cancelled`, `executed`) that is set to `pending`.

#### MultisigApproval
Update the transaction (created during the NewMultisig event), add the `approver`, update the timestamp, update the status to `approved`

#### MultisigExecuted
Update the transaction (created during the NewMultisig event), add the `last_approver` and an `executed_at` timestamp. Update the status to `executed`

#### MultisigCancelled
Update the transaction (created during the NewMultisig event), set the `canceled_by` to the address of the signer who cancelled the transaction (this field should be nullable). Update the status to `cancelled`.

**Comment by Shirku** [comment]
39f24db137e9c09465e76fc952345fc480faf69a
